### ISSUE TITLE
Query regarding saving networks. 

### ISSUE THREAD

**Issue by SumaiyaTasneem** [AkhilanB/Proper-Interpretability#1]
Hello. I have a query regarding the saved networks in the "networks" folder. Could you please tell me while saving the model weights especially ("mnist_smallgap_.......pkl") by running train.py, what epsilon value was passed through the training methods?

**Comment by AkhilanB** [comment]
Apologies for the delayed response. The epsilon values are set as follows:

MNIST: 0.3
CIFAR: 8/255
R-ImageNet: 0.003

Please let me know if you have any additional questions!
